# Generated by Django 4.0.4 on 2022-04-13 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cAbbr', models.CharField(help_text='Zadejte zkratku země např. CZE, FRA', max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Zkratka země')),
                ('cName', models.CharField(help_text='Zadejte jméno země např. Česká republika', max_length=50, unique=True, verbose_name='Jméno země')),
                ('cSystem', models.CharField(choices=[('Prezidentská republika', 'Prezidentská republika'), ('Poloprezidentská republika', 'Poloprezidentská republika'), ('Parlamentní republika', 'Parlamentní republika'), ('Konstituční monarchie', 'Konstituční monarchie'), ('Absolutní monarchie', 'Absolutní monarchie')], max_length=50, verbose_name='Státní zřízení')),
                ('cPopulation', models.IntegerField(verbose_name='Populace země')),
                ('cSummary', models.CharField(max_length=500, verbose_name='Shrnutí země')),
                ('cCapital', models.CharField(max_length=50, unique=True, verbose_name='Hlavní město')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rAbbr', models.CharField(blank=True, help_text='Zadejte zkratku kraje nebo spolkového/unijního státu např. STČ, PHA', max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Zkratka kraje nebo spolkového/unijního státu')),
                ('rName', models.CharField(help_text='Zadejte jméno regionu nebo spolkového/unijního státu', max_length=50, unique=True, verbose_name='Jméno regionu nebo spolkového/unijního státu')),
                ('rCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
            ],
            options={
                'ordering': ['rCountry__cName'],
            },
        ),
    ]
