# Generated by Django 4.0.4 on 2022-04-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_region_rpopulation_region_rregionalcapital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='cSummary',
            field=models.TextField(verbose_name='Shrnutí země'),
        ),
    ]
