# Generated by Django 4.0.4 on 2022-04-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_alter_country_csummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['cName']},
        ),
    ]
