# Generated by Django 4.0.4 on 2022-06-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_rename_country_attachment_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cArea',
            field=models.IntegerField(blank=True, default=1, verbose_name='Rozloha státu'),
        ),
        migrations.AddField(
            model_name='country',
            name='cPopulationDensity',
            field=models.IntegerField(blank=True, default=1, verbose_name='Hustota zalidnění'),
        ),
    ]
